"""Add company_id columns

Revision ID: 980f639f463d
Revises: 0fde177a3778
Create Date: 2026-02-19 18:18:55.667674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '980f639f463d'
down_revision: Union[str, Sequence[str], None] = '0fde177a3778'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_logs', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'activity_logs', 'companies', ['company_id'], ['id'])
    op.add_column('brands', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'brands', 'companies', ['company_id'], ['id'])
    op.add_column('events', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'events', 'companies', ['company_id'], ['id'])
    op.add_column('messages', sa.Column('description', sa.String(), nullable=True))
    op.add_column('users', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'company_id')
    op.drop_column('messages', 'description')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'company_id')
    op.drop_constraint(None, 'brands', type_='foreignkey')
    op.drop_column('brands', 'company_id')
    op.drop_constraint(None, 'activity_logs', type_='foreignkey')
    op.drop_column('activity_logs', 'company_id')
    # ### end Alembic commands ###
