"""add file fields to messages

Revision ID: a25e1d7f44b6
Revises: 88514e78665b
Create Date: 2026-03-06 12:52:44.046390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a25e1d7f44b6'
down_revision: Union[str, Sequence[str], None] = '88514e78665b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('file_url', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('file_name', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('file_size', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'file_size')
    op.drop_column('messages', 'file_name')
    op.drop_column('messages', 'file_url')
    # ### end Alembic commands ###
