"""Apply missing delete message columns

Revision ID: a573b7192ddc
Revises: 5bc09b810ff7
Create Date: 2026-03-17 13:11:37.380413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a573b7192ddc'
down_revision: Union[str, Sequence[str], None] = '5bc09b810ff7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('is_deleted_for_everyone', sa.Boolean(), nullable=True))
    op.add_column('messages', sa.Column('deleted_by_sender', sa.Boolean(), nullable=True))
    op.add_column('messages', sa.Column('deleted_by_receiver', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'deleted_by_receiver')
    op.drop_column('messages', 'deleted_by_sender')
    op.drop_column('messages', 'is_deleted_for_everyone')
    # ### end Alembic commands ###
